# Generated by Django 3.2.9 on 2021-11-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_create', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('cpf', models.IntegerField()),
                ('firstname', models.CharField(max_length=80)),
                ('lastname', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['cpf', 'firstname', 'lastname', 'email', 'address', 'at_create', 'at_update'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_create', models.DateTimeField(auto_now_add=True)),
                ('at_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inventory', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'value', 'inventory', 'at_create', 'at_update'],
            },
        ),
    ]
